openapi: '3.0.0'
info:
  title: e-commerce API
  description: open api for e-commerce
  contact:
    name: faliq adlan
    email: faliq67@gmail.com
  version: 1.0.0
servers:
  - url: http://{environment}.shop/
    variables:
      environment : 
          default: dev
          enum:
            - dev
            - prod
tags:
  - name: login
    description: login
  - name: user
    description: user
  - name: product
    description: product
paths:
  /login:
    post:
      tags:
        - login
      summary: login user
      description: login user
      requestBody: 
        required: true
        content:
          application/json :
            schema: 
              $ref: '#/components/schemas/login'
            example:
              email: anonim123
              password: anonim123
      responses:
        '200':
          description: success login
          content:
            application/json :
              schema :
                type: object
                properties:
                  code :
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                example:
                  code: 200
                  message: "success login"
components:
  schemas:
    login:
      type: object
      properties :
        email :
          type: string
          format: string
        password : 
          type: string
          format: string
    User :
      type : object
      properties:
        id :
          type: integer
          format: uint
        created_at :
          type: string
          format: date-time
        updated_at :
          type: string
          format : date-time
        deleted_at :
          type : string
          format: date-time
        name : 
          type: string
          format: string
        email :
          type: string
          format: string
        password : 
          type: string
          format: string
    product :
      type: object
      properties:
        id :
          type: integer
          format: uint
        created_at :
          type: string
          format: date-time
        updated_at :
          type: string
          format : date-time
        deleted_at :
          type : string
          format: date-time
        name : 
          type: string
          format: string
        price :
          type: integer
          format: int
        qty :
          type: integer
          format: int
        description :
          type: string
          format: string
  responses:
  